name: update-mc-site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 5,13 * * *'  # Run twice a day (7am and 3pm CEST)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web Apps

    env:
      GRAPH_SECRET: ${{ secrets.GRAPH_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run PowerShell script to fetch Message Center data
        shell: pwsh
        run: ./@build/Update-Site.ps1 -GraphSecret "${{ secrets.GRAPH_SECRET }}"

      - name: Build static site
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MUD_03B2C3B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."  # Root of your app
          output_location: "out"  # Where next export puts the static site
